### ISSUE TITLE
Matplotlib Support

### ISSUE THREAD

**Issue by Password-Classified** [Almenon/AREPL-vscode#406]
**Is your feature request related to a problem? Please describe.**
When I try to use `matplotlib` with AREPL (which is a *great* vscode extension, thank you) I have this error thrown up, when it runs fine normally, I have run extensive tests.

```python
TypeError: float() argument must be a string or a number, not '_NoValueType'
```

**Describe the solution you'd like**
I would like it if this error did not come up, and it just skipped, or even better, that it could show `matplotlib` graphs inline in the editor.

**Describe alternatives you've considered**
- Console ASCII graphs
- Skip error and let rest of code run

##### Thank you to the AREPL team!
@Almenon 
@yozlet 
@coder9604 
@caleb15

**Comment by Almenon** [comment]
Sorry about that, arepl doesn't always work perfectly 😬

Can you post the code that reproduces the error please?

**Comment by Password-Classified** [comment]
Thank you for replying so quickly! Here is the code.

on matplotlib import, this error is raised
```
Command failed: python -m py_compile C:\shellcheckpythonscriptpathnamethinghere.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.


Error: Command failed: python -m py_compile C:\shellcheckpythonscriptpathnamethinghere.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

Then no more code is run.

I know I have python installed, but AREPL doesn't seem to recognise it. I am on windows, so rather than `python -m py_compile`,
it should probably be `py -m py_compile`, but all other code runs. Thanks for your time. I hope that helped.

**Comment by Almenon** [comment]
What value do you have for arepl.pythonpath? Also what command do you use to run python in the terminal?

**Comment by Password-Classified** [comment]
I use `py filename.py` to run commands as I am on Windows 10. There seems to be no setting called `arepl.pythonpath`, but `python.pythonpath` is there and is set to my **python.exe** file. If it is any help, I am using Python 3.9. Thanks! 😀

**Comment by Almenon** [comment]
There should be a `arepl.pythonpath` setting, can you double-check please?

https://i.imgur.com/FuBYSB9.png

If you find the setting try putting `python.exe` or `py` in there.

**Comment by Password-Classified** [comment]
Just done that, but the same error is raised for the import of matplotlib, but nothing else

**Comment by Password-Classified** [comment]
@Almenon Could it be because of a timeout, since matplotlib takes a moment to import?

**Comment by Almenon** [comment]
AREPL does not have a timeout. Is the error happening currently the "Python was not found" error or the TypeError? What version of matplotlib do you have?

**Comment by Password-Classified** [comment]
I am using matplotlib 3.3.4. The code file has no errors in it. The error says `python -m py_compile` and says python was not found. As I said earlier, I thought that it should be py, not python, but AREPL works for me for any other file.

##### If it helps, sklearn throws the same error when any of it is imported

**Comment by Almenon** [comment]
Hmmm. And what version of python do you have?

**Comment by Password-Classified** [comment]
Python 3.9.2

**Comment by Almenon** [comment]
I'm not getting the same error a you with python 3.9.4, windows 10, matplotlib 3.3.4

Are you free for a zoom/discord call by any chance? I can understand it better in person.

**Comment by Password-Classified** [comment]
Sorry, I can't, but could upload some sort of video of what is going wrong?

**Comment by Almenon** [comment]
Darn. I'm going to be uploading a new version of arepl that uses the python specified by the python extension, that might help. Do you use the microsoft python extension?

**Comment by Password-Classified** [comment]
Yes I use the Microsoft one.

**Comment by Almenon** [comment]
I just released a new version of AREPL (v2.0.3), it should now automatically use the interpreter you have set in the python extension.

**Comment by Password-Classified** [comment]
Thank you. Will test and try this. Will it auto update in my vscode?

**Comment by Password-Classified** [comment]
I am still getting the `pythonShellSyntaxCheck` error, since it is trying to run the command `python -m` when I am on Windows 10. The windows command for python is `py`. This is the same error I get if I type `python` into the command prompt. It does not open python, but rather opens the microsoft store looking for python.

Therefore the error for me is that it is running `python -m py_compile` rather than `py -m py_compile`, since I have realised it is throwing the same error as when I type `python` into the command prompt.

Could you create a setting, that I could change so that it either runs using `py` or `python` depending on whatever you put into the setting? The default could be the default `python`, but I could change it to `py` for my purposes.

**The only unresolved thing is that it py_compiles fine for all other scripts except those that use sklearn or matplotlib.**

**Comment by Password-Classified** [comment]
Possibly a helpful note, I have nothing set as the env file.

**Comment by Password-Classified** [comment]
(in settings)

**Comment by Almenon** [comment]
Ah, I think I understand the issue now. In hindsight it was fairly obvious what was happening, but the normally the syntax check method is never called so I kinda forgot about it 😅.

Here's what happening:
AREPL ships with a setting called AREPL.pyGuiLibraries, which is a list of libraries that create a GUI (a window that pops up). Matplotlib is one of those libraries. Whenever one of those libraries are imported restart mode is activated, where AREPL is restarted every run. This is so the GUI is killed and reloaded when you make code changes. Without restart mode, if you spawned a window, the python process would hang forever until the window was killed.

Before restarting I check the syntax. Unfortunately the [syntax check](https://github.com/extrabacon/python-shell/blob/5b6c3165136bfb320615dd2e8c12fcceceeb3164/index.ts#L302) method is using the wrong python path. I need to release a new version of AREPL that fixes this. 

In the meantime you can fix it yourself with one of two ways:
1. If you don't need restartmode you can change AREPL.pyGuiLibraries to an empty list, so restart mode is never activated.
2. You can change AREPL's code to your liking. For example, you can go into `C:\<your user>\.vscode\extensions\almenon.arepl-2.0.3\node_modules\python-shell\index.js` and change line 236 in checkSyntaxFile to `const pythonPath = "py"`.

**Comment by Password-Classified** [comment]
One last issue, when I run this normally, it works.

```
import matplotlib as plt

plt.plot([1, 2, 3])
plt.show()
```

But, when I use AREPL, another error is raised... sorry.

```
File "C:\USERNAME123\  ... \Python39\lib\site-packages\numpy\core\_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: float() argument must be a string or a number, not '_NoValueType'
```

It seems to be coming from within numpy, but has no issue when run normally. Any ideas?

**Comment by Password-Classified** [comment]
As usual with programming, you fix one bug and another pops up.

**Comment by Almenon** [comment]
When I run the code you provided with matplotlib 3.3.4 and python 3.9 I get `AttributeError: module 'matplotlib' has no attribute 'plot'`.

The following works for me:
```python
from matplotlib import pyplot as plt

plt.plot([1, 2, 3])
plt.show()
```
What do you get when you run the above in AREPL vs normally?

**Comment by Password-Classified** [comment]
Sorry, i meant `import matplotlib.pyplot as plt` sorry.

**Comment by Password-Classified** [comment]
I get this error when running within AREPL, but nothing comes up when running normally. This is for your edit of the code.

```python
Traceback (most recent call last):
  line 3, in <module>
  File "C:\<USERNAMEHERE>\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 3019, in plot
    return gca().plot(
  File "C:\<USERNAMEHERE>\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 2532, in gca
    return gcf().gca(**kwargs)
  File "C:\<USERNAMEHERE>\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\figure.py", line 1522, in gca
    return self.add_subplot(1, 1, 1, **kwargs)
  File "C:\<USERNAMEHERE>\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\figure.py", line 781, in add_subplot
    ax = subplot_class_factory(projection_class)(self, *args, **pkw)
  File "C:\<USERNAMEHERE>\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\axes\_subplots.py", line 38, in __init__
    self.set_subplotspec(SubplotSpec._from_subplot_args(fig, args))
  File "C:\<USERNAMEHERE>\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\axes\_subplots.py", line 72, in set_subplotspec
    self._set_position(subplotspec.get_position(self.figure))
  File "C:\<USERNAMEHERE>\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\_api\deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "C:\<USERNAMEHERE>\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\gridspec.py", line 743, in get_position
    fig_bottom = fig_bottoms[rows].min()
  File "C:\<USERNAMEHERE>\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: float() argument must be a string or a number, not '_NoValueType'
```

**Comment by Almenon** [comment]
What version of numpy do you have?

**Comment by Password-Classified** [comment]
Numpy V1.19.5

**Comment by Almenon** [comment]
It works for me, not sure why you're getting the error, sorry :(

**Comment by Password-Classified** [comment]
Should we leave this issue for now, it doesn't seem to be getting anywhere. I think I'll let you get on with developing it/other projects further.

**Comment by Password-Classified** [comment]
I have just realised, that AREPL would probably open a new matplotlib figure window rather than show it inline, so I don't think this is worth continuing, but thank you so much for the help, and thanks, I'll still love using AREPL for other projects.

**Comment by Almenon** [comment]
> that AREPL would probably open a new matplotlib figure window rather than show it inline

Unfortunately that is correct. For inline functionality I suggest using Jupiter notebook or the Jupiter notebook vscode extension. Sorry about that! 

> I'll still love using AREPL for other projects

Glad to hear it :)
